---

- name: EL 7 | Create systemd tomcat.service
  template:
    src: el7/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  tags:
    - setup

- name: Start tomcat service
  systemd:
    name: tomcat
    daemon_reload: yes
    state: started
    enabled: yes
  tags:
    - setup
